[[permission]]
identifier = "allow-app-commands"
description = "Enables access to core OSTP commands"

[permission.commands]
allow = [
  "start_tunnel",
  "stop_tunnel",
  "get_tunnel_status",
  "get_metrics",
  "get_config",
  "save_config",
  "get_wintun_install_path",
  "set_autostart",
  "get_autostart"
]
